In [84]:
# Test till optimering av segmentation.py

import cv2
import numpy as np
import glob
import random
from matplotlib import pyplot as plt

from remove_frame.removeFrame import removeFrame
from proximity import jaccard_binary
import segmentation2


In [86]:
path = r'C:\Users\johan\Desktop\Images\Images\IMG_20221101_125559.jpg'
outputFolder = r'C:\Users\johan\Desktop\Images\Images\egenMask\opti'
mMaskPath = r'C:\Users\johan\Desktop\Images\Images\egenMask\IMG_20221101_125559_mask.jpg'


lims = np.array([[0, .7, 0], 
                 [.25, 1, 1],
                 [0.62, .6, 0],
                 [1, 1, 1],
                 [0, .7, .05],
                 [1, .1, 1]])
limsOpti = np.array([1.44973853e+00, 1.15896675e-01, 3.69226545e-01, 1.50774009e+00,
       1.19786395e+00, 1.50411713e+00, 5.38750636e-04, 8.42607118e-01,
       8.47274583e-01, 1.50398356e+00, 1.24217183e+00, 1.54272547e+00,
       8.98821975e-01, 2.51493316e-01, 6.02271146e-01, 2.07489848e+00,
       5.44882928e-01, 1.50374793e+00])
lims = lims.flatten()
allLims = lims[:, np.newaxis]

lims = np.multiply(255,lims)
lims = lims.astype(int)

# Runs once with original Lims
%run segmentation2.py {path}

tMaskPath = r'C:\Users\johan\Desktop\Images\Images\result\IMG_20221101_125559_mask.jpg' # the test mask
tMask = cv2.imread(tMaskPath)
mMask = cv2.imread(mMaskPath) # the manual mask

jac = jaccard_binary(tMask,mMask)
print(jac)

processImage(path,lims)
tMaskPath = r'C:\Users\johan\Desktop\Images\Images\result\IMG_20221101_125559_mask.jpg' # the test mask
tMask = cv2.imread(tMaskPath)
jac = jaccard_binary(tMask,mMask)
print(jac)



['segmentation2.py', 'C:\\Users\\johan\\Desktop\\Images\\Images\\IMG_20221101_125559.jpg']
2
0.04070671675403171
0.05673839509180437


In [61]:
from scipy.optimize import minimize, LinearConstraint
n_buyers = 10
n_shares = 15
np.random.seed(10)
prices = np.random.random(n_buyers)
money_available = np.random.randint(1, 4, n_buyers)
n_shares_per_buyer = money_available / prices
print(prices, money_available, n_shares_per_buyer, sep="\n")
constraint = LinearConstraint(np.ones(n_buyers), lb=n_shares, ub=n_shares)
bounds = [(0, n) for n in n_shares_per_buyer]
def objective_function(x, prices):
    return -x.dot(prices)

res = minimize(
    objective_function,
    x0=10 * np.random.random(n_buyers),
    args=(prices,),
    constraints=constraint,
    bounds=bounds,
)

[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701 0.22479665
 0.19806286 0.76053071 0.16911084 0.08833981]
[1 1 1 3 1 3 3 2 1 1]
[ 1.29647768 48.18824404  1.57816269  4.00638948  2.00598984 13.34539487
 15.14670609  2.62974258  5.91328161 11.3199242 ]


In [68]:
from scipy.optimize import minimize, LinearConstraint
print(np.shape(lims))
bounds = [(0, 255) for n in range(np.size(lims))]
constraint = LinearConstraint((lims-lims.astype(int) == 0)*1, lb = 18, ub = 18)
def objective_function(lims):
    lims = lims.astype(int)
    processImage(path,lims)
    jac = jaccard_binary(tMask,mMask)
    print(lims)
    return -jac

(18,)


In [76]:
print("Start")
results = minimize(
    objective_function,
    x0 = lims,
    method='trust-constr',
    #args=(lims,),
    constraints=constraint,
    bounds=bounds,
)

Start
[255 178   0  63 255 255 158 153   0 255 255 255   0 178  12 255  25 255]
[255 178   0  63 255 255 158 153   0 255 255 255   0 178  12 255  25 255]
[255 178   0  63 255 255 158 153   0 255 255 255   0 178  12 255  25 255]
[255 178   0  63 255 255 158 153   0 255 255 255   0 178  12 255  25 255]
[255 178   0  63 255 255 158 153   0 255 255 255   0 178  12 255  25 255]
[255 178   0  63 255 255 158 153   0 255 255 255   0 178  12 255  25 255]
[255 178   0  63 255 255 158 153   0 255 255 255   0 178  12 255  25 255]
[255 178   0  63 255 255 158 153   0 255 255 255   0 178  12 255  25 255]
[255 178   0  63 255 255 158 153   0 255 255 255   0 178  12 255  25 255]
[255 178   0  63 255 255 158 153   0 255 255 255   0 178  12 255  25 255]
[255 178   0  63 255 255 158 153   0 255 255 255   0 178  12 255  25 255]
[255 178   0  63 255 255 158 153   0 255 255 255   0 178  12 255  25 255]
[255 178   0  63 255 255 158 153   0 255 255 255   0 178  12 255  25 255]
[255 178   0  63 255 255 158 153

In [78]:
results

 barrier_parameter: 1.0240000000000006e-08
 barrier_tolerance: 1.0240000000000006e-08
          cg_niter: 778
      cg_stop_cond: 0
            constr: [array([18.]), array([1.44973853e+00, 1.15896675e-01, 3.69226545e-01, 1.50774009e+00,
       1.19786395e+00, 1.50411713e+00, 5.38750636e-04, 8.42607118e-01,
       8.47274583e-01, 1.50398356e+00, 1.24217183e+00, 1.54272547e+00,
       8.98821975e-01, 2.51493316e-01, 6.02271146e-01, 2.07489848e+00,
       5.44882928e-01, 1.50374793e+00])]
       constr_nfev: [0, 0]
       constr_nhev: [0, 0]
       constr_njev: [0, 0]
    constr_penalty: 1.0
  constr_violation: 1.5276668818842154e-13
    execution_time: 3961.4914486408234
               fun: -0.010401219532259877
              grad: array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0.])
               jac: [array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]), array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.

In [50]:
lims-lims.astype(int) == 0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True])

In [8]:
tMaskPath[:]

'C:\\Users\\johan\\Desktop\\Images\\Images\\result\\IMG_20221101_125559_mask.jpg'

In [9]:
np.size(lims)


18

In [67]:
(lims-lims.astype(int) == 0)*1

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [80]:
xres = np.array([1.44973853e+00, 1.15896675e-01, 3.69226545e-01, 1.50774009e+00,
       1.19786395e+00, 1.50411713e+00, 5.38750636e-04, 8.42607118e-01,
       8.47274583e-01, 1.50398356e+00, 1.24217183e+00, 1.54272547e+00,
       8.98821975e-01, 2.51493316e-01, 6.02271146e-01, 2.07489848e+00,
       5.44882928e-01, 1.50374793e+00])

In [81]:
xres

array([1.44973853e+00, 1.15896675e-01, 3.69226545e-01, 1.50774009e+00,
       1.19786395e+00, 1.50411713e+00, 5.38750636e-04, 8.42607118e-01,
       8.47274583e-01, 1.50398356e+00, 1.24217183e+00, 1.54272547e+00,
       8.98821975e-01, 2.51493316e-01, 6.02271146e-01, 2.07489848e+00,
       5.44882928e-01, 1.50374793e+00])